### ISSUE TITLE
how do i use the farmboye?

### ISSUE THREAD

**Issue by bgmxxx** [bearkillerPT/pokeMMOFarmBoye#1]

**Comment by bearkillerPT** [comment]
Basic explanation: 
You need to have python3 installed and install using pip3 the libraries that are being imported in the main script [farm.py](https://github.com/bearkillerPT/pokeMMOFarmBoye/blob/main/farm.py). The you have in that same script a few different functions for farming:
- farmPayday is supposed to be used on island 5 
- farmEXPIsland2 is for farming psyducks hordes 
- farmAbras walks up and down and if it detects an abra it will try to stunspore it and then use a pokeball

Please keep in mind that selecting abilities is done with the keyboard and not with image detection.
You should start by choosing the function you want and see the images it uses and try to adapt it. Try to understand when you're in combact to select the correct ability and have fun!

**Comment by bearkillerPT** [comment]
I usually just have a small powershell opened on the bottom of the screen and the game on top part (windowed mode/not fullscreen)

**Comment by bearkillerPT** [comment]
Looks stale to me 😂
